# Generated by Django 5.0 on 2025-09-25 11:17

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('declaracao_simples', 'Declaração Simples'), ('declaracao_laboral', 'Declaração Laboral/Financeira'), ('declaracao_complexa', 'Declaração Complexa'), ('contrato_simples', 'Contrato Simples'), ('contrato_servicos', 'Contrato de Prestação de Serviços'), ('contrato_complexo', 'Contrato Complexo'), ('fatura_simples', 'Fatura Simples'), ('fatura_comercial', 'Fatura Comercial'), ('documento_auxiliar', 'Documento Auxiliar'), ('cv_basico', 'CV Básico'), ('cv_profissional', 'CV Profissional'), ('cv_multilingue', 'CV Multilíngue'), ('contract', 'Contrato'), ('invoice', 'Factura'), ('report', 'Relatório'), ('certificate', 'Certificado')], max_length=50)),
                ('subcategory', models.CharField(blank=True, default='', max_length=100)),
                ('price_kz', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('fields', models.JSONField(default=dict)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('pdf', 'PDF'), ('docx', 'Word'), ('xlsx', 'Excel')], max_length=10)),
                ('data', models.JSONField(default=dict)),
                ('status', models.CharField(choices=[('pending', 'Pendente'), ('processing', 'Processando'), ('completed', 'Completado'), ('failed', 'Falha')], default='pending', max_length=20)),
                ('file_url', models.URLField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to=settings.AUTH_USER_MODEL)),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='documents.template')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
